spring.datasource:
  url: jdbc:mysql://192.168.159.131:3306/test
  username: root
  password: password
  driver-class-name: com.mysql.jdbc.Driver

spring.jpa.database: MYSQL
# Show or not log for each sql query
spring.jpa.show-sql: true
# Hibernate ddl auto (create, create-drop, update)
spring.jpa.hibernate.ddl-auto: update
# Naming strategy
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

# stripped before adding them to the entity manager)
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

spring.thymeleaf.cache: false

spring.messages.basename: i18n/messages
spring.messages.cache-seconds: 3600
spring.messages.encoding: UTF-8

spring.devtools.restart.additional-paths: src/main/java

gender:
  male: '{"value": 0, "display": "Male", "i18n": "gender.male"}'
  female: '{"value": 1, "display": "Female", "i18n": "gender.female"}'

mail: 
  host: localhost
  port: 25
  smtp: 
    auth: false
    starttls-enable: false
  from: me@localhost
  username: test
  password: test